In [2]:
import numpy as np

In [3]:
rho = np.array([[0.45,0.2-1j*0.3],[0.2+1j*0.3,0.55]])

In [4]:
e_val, e_vec = np.linalg.eigh(rho)

In [5]:
e_vec

array([[-0.75410893-0.j        , -0.65674936+0.j        ],
       [ 0.364299  +0.5464485j , -0.41830437-0.62745656j]])

In [6]:
np.linalg.norm(e_vec[:,0])

1.0000000000000002

In [7]:
vec_0 = np.exp(1j*np.pi)*e_vec[:,0]

In [8]:
vec_1 = np.exp(1j*np.pi)*e_vec[:,1]

In [9]:
vec_0

array([ 0.75410893-9.23517090e-17j, -0.364299  -5.46448496e-01j])

In [10]:
vec_1

array([0.65674936-8.04285998e-17j, 0.41830437+6.27456559e-01j])

In [11]:
e_val[0]

0.13599450553597417

In [12]:
e_val[1]

0.8640054944640259

In [13]:
np.abs(vec_1[1])

0.7541089324324072

In [14]:
0.657**2 + abs(0.418+0.627*1j)**2

0.999502

In [16]:
np.angle(0.418+1j*0.627)

0.982793723247329

In [24]:
np.angle(-0.364-1j*0.546)+2*np.pi

4.124386376837123